language: go

go:
  - "1.9"
  - "1.10.x"

env:
  - PGURL="postgres://postgres:""@127.0.0.1:5432/scheduler"

services:
  - postgresql

addons:
  postgresql: '9.5'

before_script:
  - cp .env.travis .env

before_install:
  - psql -c 'create database scheduler;' -U postgres
  - psql -U postgres -d scheduler -f ./db/migrations/setup.sql

script: 
  - go install
  - go test ./...