sh 'go get github.com/antonlindstrom/pgstore'
sh 'go get github.com/gorilla/context'
sh 'go get github.com/gorilla/csrf'
sh 'go get github.com/gorilla/mux'
sh 'go get github.com/lib/pq'
sh 'go get github.com/rs/cors'
sh 'go get github.com/urfave/negroni'